In [2]:
from pathlib import Path
import sys  

# Get my_package directory path from Notebook
parent_dir = str(Path().resolve().parents[0])
print(parent_dir)
# Add to sys.path

path_set = set(sys.path)
if parent_dir not in path_set:
    sys.path.insert(0, parent_dir)

print(sys.path)

/Users/colinbull/appdev/dfe/sfb/education-benchmarking-and-insights/data-pipeline
['/Users/colinbull/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/241.17890.14/PyCharm.app/Contents/plugins/python/helpers-pro/jupyter_debug', '/Users/colinbull/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/241.17890.14/PyCharm.app/Contents/plugins/python/helpers/pydev', '/Users/colinbull/appdev/dfe/sfb/education-benchmarking-and-insights/data-pipeline', '/Users/colinbull/.pyenv/versions/3.11.4/lib/python311.zip', '/Users/colinbull/.pyenv/versions/3.11.4/lib/python3.11', '/Users/colinbull/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload', '', '/Users/colinbull/Library/Caches/pypoetry/virtualenvs/fbit-data-pipeline-aJYNke-B-py3.11/lib/python3.11/site-packages']

# VMFI Data processing pipeline

This workbook aims to emulate the current data processing pipeline that occurs in VMFI pipeline. The logic and processing is largely based on the following document [Insights data portal - Data sources and sql analysis](https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/VMFI/_layouts/15/Doc.aspx?sourcedoc=%7B38C1DC37-7CDB-48B8-9E22-284F4F311C0B%7D&file=1.%20Insights%20portal%20-%20data%20sources%20and%20sql%20analysis%20v010%20-%20Copy.docx&action=default&mobileredirect=true) and will stay true to this document even if the existing stored procedures are doing something different. This will form the basis of a gap analysis going forward. 

All data loaded in the following workbook comes from the set of CSV files in the `data` folder alongside this workbook. These datasets are for the most part from the list at the start of the linked document. However, because there is additional standing data required to fully implement the pipeline then this data has been exported from the development VMFI pipeline database. These files are currently: 

| File name | DB Table |
|:----------|----------|
|standing_data_cdc.csv | standing_data.cdc |

In [3]:
import src.pipeline.pre_processing as pre_processing
import pandas as pd
import numpy as np
import time

In [4]:
# Create and clean directory
from pathlib import Path
Path("output/pre-processing").mkdir(parents=True, exist_ok=True)

# files = glob.glob("output/pre-processing/*")
# for f in files:
#     os.remove(f)

In [5]:
start_time = time.time()
current_year = 2022

## CDC data load and preparation

School buildings condition dataset. Based on the surveys performed throughout 2018-2019.

The data in the file `data/standing_data_cdc.csv` is just an export of the data in `standing_data.cdc` table. Without the Year and Import ID fields. In future this will likely have to be read directly from the source database as per [this document.](https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/VMFI/_layouts/15/Doc.aspx?sourcedoc=%7B38C1DC37-7CDB-48B8-9E22-284F4F311C0B%7D&file=1.%20Insights%20portal%20-%20data%20sources%20and%20sql%20analysis%20v010%20-%20Copy.docx&action=default&mobileredirect=true)

In [6]:
cdc = pre_processing.prepare_cdc_data('data/cdc.csv', current_year)

In [7]:
#cdc.to_csv('output/pre-processing/cdc.csv')
cdc

        Total Internal Floor Area  Age Average Score  Building Age
URN
100150                     2803.0          48.358188          1988
100162                     2105.0         133.162945          1880
100164                     2934.0               97.0          1925
100166                     2040.0          91.705882          1947
105304                     1602.0          35.752809          1985
...                           ...                ...           ...
144913                     3111.0          16.704275          2008
144917                     2620.0          78.412214          1960
105623                     3382.0                7.0          2015
144918                     4733.0          19.009296          1997
144919                     1762.0          38.370602          1978

[22733 rows x 3 columns]

## School Census data load

*Pupil Census* - DfE data collection providing information about school and pupil characteristics, for example percentage of pupils claiming free school`z meals, or having English as their second language. 

*Workforce census* - Single reference for all school workforce statistics based on staff working in publicly funded schools in England.

The following code loads both the workforce and pupil census data and preforms an `inner` join by URN on the data sets.

In [8]:
census = pre_processing.prepare_census_data('data/census_workforce.xlsx', 'data/census_pupils.csv')

In [9]:
#census.to_csv('output/pre-processing/census.csv')
census

,region_name,district_administrative_name,ward_name,Full time girls Year group 12,Full time girls Year group 13,Full time boys Year group 12,Full time boys Year group 13,Number of early year pupils (years E1 and E2),Number of nursery pupils (years N1 and N2),Number of pupils,...,Total Number of Auxiliary Staff (Headcount),Total School Workforce (Full-Time Equivalent),Total Number of Teachers in the Leadership Group (Full-time Equivalent),Total Number of Teachers (Full-Time Equivalent),Total Number of Teaching Assistants (Full-Time Equivalent),NonClassroomSupportStaffFTE,Total Number of Auxiliary Staff (Full-Time Equivalent),Teachers with Qualified Teacher Status (%) (Headcount),TotalPupilsNursery,TotalPupilsSixthForm
URN,,,,,,,,,,,,,,,,,,,,,
141334,East Midlands,Nottingham,Bilborough,0.0,0.0,0.0,0.0,0.0,0.0,325.0,...,13.0,34.17,2.64,13.11,10.29,4.82,5.95,100.000000,0.0,0.0
141396,East Midlands,Nottingham,Aspley,0.0,0.0,0.0,0.0,0.0,57.0,642.0,...,34.0,82.47,4.00,34.00,29.55,10.13,8.79,100.000000,57.0,0.0
141397,East Midlands,Nottingham,Bilborough,0.0,0.0,0.0,0.0,0.0,44.0,500.0,...,27.0,72.81,4.24,24.55,31.84,6.55,9.87,100.000000,44.0,0.0
142223,East Midlands,Nottingham,Wollaton West,0.0,0.0,0.0,0.0,0.0,70.0,1117.0,...,47.0,99.66,4.16,47.12,33.07,6.57,12.90,100.000000,70.0,0.0
144396,East Midlands,Nottingham,Bulwell,0.0,0.0,0.0,0.0,0.0,21.0,217.0,...,11.0,25.57,2.00,11.39,7.36,4.00,2.82,100.000000,21.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104642,North West,Liverpool,Church,0.0,0.0,0.0,0.0,0.0,0.0,421.0,...,18.0,34.47,3.60,15.80,6.27,5.22,7.18,100.000000,0.0,0.0
104643,North West,Liverpool,Cressington,0.0,0.0,0.0,0.0,0.0,28.0,432.0,...,19.0,39.89,3.00,17.40,11.74,3.34,7.41,100.000000,28.0,0.0
104645,North West,Liverpool,Tuebrook and Stoneycroft,0.0,0.0,0.0,0.0,0.0,0.0,237.0,...,10.0,26.47,3.00,12.40,6.78,3.19,4.10,92.307692,0.0,0.0
104646,North West,Liverpool,St Michael's,0.0,0.0,0.0,0.0,0.0,18.0,194.0,...,5.0,22.36,2.00,12.00,6.24,1.44,2.68,100.000000,18.0,0.0
104648,North West,Liverpool,Picton,0.0,0.0,0.0,0.0,0.0,16.0,186.0,...,11.0,22.01,2.00,8.20,4.55,2.42,6.84,100.000000,16.0,0.0

## Special Education Needs (SEN) data load and preparation

Special educational needs dataset. Contains information about the number of pupils, who require various SEN provisions. This loads the `SEN` data, which originates from [here](https://explore-education-statistics.service.gov.uk/find-statistics/special-educational-needs-in-england#dataDownloads-1)

In [10]:
sen = pre_processing.prepare_sen_data('data/sen.csv')

In [11]:
#sen.to_csv("output/pre-processing/sen.csv")
sen

,EHC plan,SEN support,Percentage SEN,Percentage with EHC,Percentage without EHC,Percentage Primary Need SPLD,Percentage Primary Need MLD,Percentage Primary Need SLD,Percentage Primary Need PMLD,Percentage Primary Need SEMH,Percentage Primary Need SLCN,Percentage Primary Need HI,Percentage Primary Need VI,Percentage Primary Need MSI,Percentage Primary Need PD,Percentage Primary Need ASD,Percentage Primary Need OTH
URN,,,,,,,,,,,,,,,,,
100000,8.0,59.0,24.723247,2.952030,21.771218,0.738007,1.476015,0.0,0.000000,3.321033,11.439114,0.738007,0.000000,0.738007,0.000000,3.321033,0.369004
100001,0.0,22.0,2.976996,0.000000,2.976996,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
100002,0.0,22.0,8.178439,0.000000,8.178439,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
100003,0.0,145.0,13.875598,0.000000,13.875598,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
100005,2.0,23.0,18.382353,1.470588,16.911765,0.000000,0.000000,0.0,0.735294,0.000000,0.000000,0.000000,0.000000,0.000000,0.735294,16.176471,0.735294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149557,3.0,2.0,12.195122,7.317073,4.878049,4.878049,0.000000,0.0,0.000000,0.000000,2.439024,0.000000,0.000000,0.000000,0.000000,4.878049,0.000000
149632,58.0,136.0,15.027111,4.492641,10.534469,2.401239,1.161890,0.0,0.000000,1.549187,1.936483,0.619675,0.309837,0.077459,0.542215,2.013943,1.781565
149633,0.0,7.0,8.139535,0.000000,8.139535,2.325581,1.162791,0.0,0.000000,1.162791,1.162791,0.000000,0.000000,0.000000,0.000000,1.162791,1.162791
149635,10.0,30.0,6.116208,1.529052,4.587156,2.293578,0.152905,0.0,0.000000,1.834862,0.305810,0.305810,0.305810,0.000000,0.000000,0.305810,0.611621
149636,8.0,76.0,45.161290,4.301075,40.860215,2.688172,11.290323,0.0,0.000000,8.064516,6.989247,0.000000,0.000000,0.000000,0.537634,1.075269,14.516129

## KS2 and KS4 processing

In [12]:
ks2 = pre_processing.prepare_ks2_data('data/ks2.xlsx')

In [13]:
#ks2.to_csv('output/pre-processing/ks2.csv')
ks2

        Ks2Progress
URN
100000          0.5
136807         13.0
139837         20.7
140686         -1.8
100008          5.5
...             ...
143723        -28.9
146250        -20.5
141993          0.0
112465          0.0
112466          0.0

[16059 rows x 1 columns]

In [14]:
ks4 = pre_processing.prepare_ks4_data('data/ks4.xlsx')

In [15]:
#ks4.to_csv('output/pre-processing/ks4.csv')
ks4

        AverageAttainment  Progress8Measure    Progress8Banding
URN
100053               50.3             -0.16             Average
100054               65.8              0.77  Well above average
100052               44.6             -0.03             Average
100092                0.5             -2.22  Well below average
100049               41.7             -0.28       Below average
...                   ...               ...                 ...
112465                0.5             -1.53  Well below average
137269               50.2              0.36             Average
112393               40.3             -0.11             Average
112385               51.2              0.12             Average
141041               40.6             -0.84  Well below average

[3492 rows x 3 columns]

## AR Data load and preparation

This loads the Annual accounts return dataset and the corresponding mapping file. This extract only contains benchmarking section, which consists of submissions of costs, income, and balances of individual academies.

The mapping file, contains the mapping from AR4 cell references to cost categories and descriptions.

In [16]:
academy_ar = pre_processing.prepare_aar_data('data/AR7_BenchmarkReport_2022.csv')
central_services = pre_processing.prepare_central_services_data('data/AR7_CS_BenchmarkReport_2022.csv')

ValueError: Usecols do not match columns, columns expected but not found: ['BNCH11123-BAI011-A (Academies - Income)']

In [ ]:
#academy_ar.to_csv('output/pre-processing/academy_ar.csv')
academy_ar

In [ ]:
central_services

Create a summary table for the AR stance of each distinct academy in the table.

Now compute the trust financial position in the same manor as the individual academy position

## Academy and maintained schools data load and preparation

This reads the main GIAS data (edubasealldataYYYYMMDD file) and the associated links file (links_edubasealldataYYYYMMDD file). This is taken from the [GIAS Service](https://get-information-schools.service.gov.uk/help)

Other columns are tidied up by asserting the correct type for that column. This is tidying phase is largly because on load integer columns will be inferred to be a float as opposed to an integer.

In [ ]:
schools = pre_processing.prepare_schools_data('data/gias.csv','data/gias_links.csv')

In [ ]:
#schools.to_csv('output/pre-processing/schools.csv')
schools.sort_index()

In [ ]:
cfo = pre_processing.build_cfo_data('data/cfo.xlsx')

Merge required GIAS, census, sen, cdc, PFI, and arr data with the base academy data

In [ ]:
academies = pre_processing.build_academy_data('data/academy_master_list.csv', 'data/gias_all_links.csv',
                                              current_year, schools, census, sen, cdc, 
                                              academy_ar, ks2, ks4, cfo, central_services)

In [ ]:
#academies.to_csv('output/pre-processing/academies.csv')
academies.loc[133768].sort_index()

Merge required census and cdc data to the maintained schools data set

In [ ]:
# Load raw list from CSV
maintained_schools = pre_processing.build_maintained_school_data('data/maintained_schools_master_list.csv','data/gias_all_links.csv',current_year, schools, census, sen, cdc, ks2, ks4)

In [ ]:
maintained_schools.to_csv('output/pre-processing/maintained_schools.csv')
#maintained_schools

In [ ]:
all_schools = pd.concat([academies,maintained_schools])

In [ ]:
all_schools[all_schools["Is PFI"].isna()]

## Federation Capture

In [ ]:
(hard_federations, soft_federations) = pre_processing.build_federations_data('data/gias_all_links.csv', maintained_schools.reset_index())

In [ ]:
hard_federations.to_csv('output/pre-processing/hard_federations.csv')
hard_federations

In [ ]:
soft_federations.to_csv('output/pre-processing/soft_federations.csv')
soft_federations[['LAEstab']]

# Budget Forcast Returns

In [ ]:
year = 2023

bfr_cell_mapping_cols = {'EFALineNo':'Int64','balance_flag':'Int64'}

bfr_sofa_cols = {'TrustUPIN':'Int64','CreatedBy':'string','Category':'string','Title':'string','EFALineNo':'Int64','Y1P1':'float','Y1P2':'float','Y2P1':'float','Y2P2':'float'}
bfr_3y_cols = {'TrustUPIN':'Int64','EFALineNo':'Int64','Y2':'Int64','Y3':'Int64','Y4':'Int64'}


def _calculate_metrics(bfr):
    bfr_metrics = bfr[['TrustUPIN']].copy().set_index('TrustUPIN')
    bfr_metrics['Revenue reserve as percentage of income'] =\
          round(bfr[bfr['Title']=='Revenue reserves'].set_index('TrustUPIN')[['Y1']]
                /bfr[bfr['Title']=='Total income'].set_index('TrustUPIN')[['Y1']]*100,1)
    bfr_metrics['Staff costs as percentage of income'] =\
          round(bfr[bfr['Title']=='Staff costs'].set_index('TrustUPIN')[['Y1']]
                /bfr[bfr['Title']=='Total income'].set_index('TrustUPIN')[['Y1']]*100,1)
    bfr_metrics['Expenditure as percentage of income'] =\
          round(bfr[bfr['Title']=='Total expenditure'].set_index('TrustUPIN')[['Y1']]
                /bfr[bfr['Title']=='Total income'].set_index('TrustUPIN')[['Y1']]*100,1)
    bfr_metrics['percent self-generated income'] =\
          round(bfr[bfr['Title']=='Self-generated income'].set_index('TrustUPIN')[['Y1']]/
                (bfr[bfr['Title']=='Self-generated income'].set_index('TrustUPIN')[['Y1']] +
                  bfr[bfr['Title']=='Grant funding'].set_index('TrustUPIN')[['Y1']])*100,0)
    bfr_metrics['percent grant funding'] = 100 - bfr_metrics['percent self-generated income']
    return bfr_metrics

def _calculate_slopes(matrix):
    x = np.array([1,2,3,4,5,6])
    x_bar = 3.5
    x_x_bar = x - x_bar
    y_bar = np.mean(matrix, axis=1)
    y_y_bar = matrix - np.vstack(y_bar)
    slope_array = np.sum(x_x_bar*y_y_bar,axis=1)/np.sum(x_x_bar**2)
    return slope_array

def _assign_slope_flag(df):
    percentile_10 = np.nanpercentile(df['slope'].values, 10)
    percentile_90 = np.nanpercentile(df['slope'].values, 90)
    df['slope_flag'] = 0
    df.loc[df['slope'] < percentile_10, 'slope_flag'] = -1
    df.loc[df['slope'] > percentile_90, 'slope_flag'] = 1
    return df


def _slope_analysis(bfr_dataframe, academies_y2, academies_y1):

    year_columns = ['Y-2','Y-1','Y1','Y2','Y3','Y4']
    bfr_revenue_reserves = bfr_dataframe[bfr_dataframe['Title']=='Revenue reserves']
    bfr_pupil_numbers = bfr_dataframe[bfr_dataframe['Title']=='Pupil numbers']

    

    # TODO need to add in historic data to this, filling in fake values for now
    bfr_revenue_reserves = pd.merge(
        bfr_revenue_reserves, 
        academies_y2[['Trust UPIN','Trust Balance']].rename(columns={
            'Trust UPIN':'TrustUPIN',
            'Trust Balance':'Y-2'
            }).drop_duplicates(), how='left', on='TrustUPIN')
    
    bfr_revenue_reserves = pd.merge(
        bfr_revenue_reserves, 
        academies_y1[['Trust UPIN','Trust Balance']].rename(columns={
                'Trust UPIN':'TrustUPIN',
                'Trust Balance':'Y-1'
                }).drop_duplicates(), how='left', on='TrustUPIN')
    
    bfr_pupil_numbers = pd.merge(
        bfr_pupil_numbers, 
        academies_y2[['Trust UPIN','Number of pupils']].rename(columns={
            'Trust UPIN':'TrustUPIN',
            'Number of pupils':'Y-2'
            }).groupby('TrustUPIN').agg(sum), how='left', on='TrustUPIN')
    
    bfr_pupil_numbers = pd.merge(
        bfr_pupil_numbers, 
        academies_y2[['Trust UPIN','Number of pupils']].rename(columns={
            'Trust UPIN':'TrustUPIN',
            'Number of pupils':'Y-1'
            }).groupby('TrustUPIN').agg(sum), how='left', on='TrustUPIN')


    # convert to matrix
    matrix_revenue_reserves = bfr_revenue_reserves[year_columns].values.astype(float)
    matrix_pupil_numbers = bfr_pupil_numbers[year_columns].values.astype(float)

    matrix_revenue_reserves_per_pupil = matrix_revenue_reserves/matrix_pupil_numbers

    # determine associated slopes
    bfr_revenue_reserves['slope'] = _calculate_slopes(matrix_revenue_reserves)

    bfr_revenue_reserves_per_pupil = bfr_revenue_reserves[['CreatedBy','Category','Title','EFALineNo']].copy()
    bfr_revenue_reserves_per_pupil['slope'] = _calculate_slopes(matrix_revenue_reserves_per_pupil)
    for i in range(len(year_columns)):
        bfr_revenue_reserves_per_pupil[year_columns[i]] = matrix_revenue_reserves_per_pupil.T[i]


    # flag top 10% and bottom 90% percent of slopes with -1 and 1 respectively
    bfr_revenue_reserves = _assign_slope_flag(bfr_revenue_reserves)
    bfr_revenue_reserves_per_pupil = _assign_slope_flag(bfr_revenue_reserves_per_pupil)

    return bfr_revenue_reserves, bfr_revenue_reserves_per_pupil

def _volatility_analysis(bfr):
    bfr['volatility'] = (bfr['Trust Balance'] - bfr['Y1P2'])/abs(bfr['Trust Balance'])

    volatility_conditions = [(bfr['volatility'] <= -0.05),
                            (bfr['volatility'] <= 0.05),
                            (bfr['volatility'] <= 0.1),
                            (bfr['volatility'] > 0.1)]
    volatility_messages = ["AR below forecast", 
                        "stable forecast", 
                        "AR above forecast", 
                        "AR significantly above forecast"]

    bfr['volatility_status'] = np.select(volatility_conditions, volatility_messages, default='')
    return bfr

def build_bfr_data(bfr_sofa_data_path,bfr_3y_data_path, academies_y2, academies_y1, academies):

    bfr_sofa = pd.read_csv(
        bfr_sofa_data_path,
        encoding='unicode-escape',
        dtype=bfr_sofa_cols,
        usecols=bfr_sofa_cols.keys(),
    )

    bfr_3y = pd.read_csv(
        bfr_3y_data_path,
        encoding='unicode-escape',
        dtype=bfr_3y_cols,
        usecols=bfr_3y_cols.keys(),
    )    


    # remove unused metrics
    bfr_sofa = bfr_sofa[bfr_sofa['EFALineNo'].isin([298,430,335,380,211,220,199,200,205,210,999])]

    self_gen_income = bfr_sofa[
        bfr_sofa['EFALineNo'].isin([211,220])
        ].groupby('TrustUPIN')[['Y1P1','Y1P2','Y2P1','Y2P2']].sum().reset_index()
    self_gen_income['Title'] = 'Self-generated income'

    grant_funding = bfr_sofa[
        bfr_sofa['EFALineNo'].isin([199,200,205,210])
        ].groupby('TrustUPIN')[['Y1P1','Y1P2','Y2P1','Y2P2']].sum().reset_index()
    grant_funding['Title'] = 'Grant funding'

    bfr_sofa = bfr_sofa[~bfr_sofa['EFALineNo'].isin([211,220,199,200,205,210])]
    bfr_sofa = pd.concat([bfr_sofa, self_gen_income, grant_funding])
    bfr_sofa['Title'].replace({
        'Balance c/f to next period ':'Revenue reserves',
        'Pupil numbers (actual and estimated)':'Pupil numbers',
        'Total revenue expenditure':'Total expenditure',
        'Total revenue income':'Total income','Total staff costs':'Staff costs'
        }, inplace=True)
    bfr_sofa['Y1'] = bfr_sofa['Y1P1'] + bfr_sofa['Y1P2']
    bfr_sofa.drop_duplicates(inplace=True)
    
    bfr_3y['EFALineNo'].replace({2980:298,4300:430,3800:380,9000:999}, inplace=True)
    bfr_3y = bfr_3y[bfr_3y['EFALineNo'].isin([298,430,335,380,999])]
    bfr_3y.drop_duplicates(inplace=True)
    

    bfr = pd.merge(bfr_sofa, bfr_3y, how='left', on=('TrustUPIN','EFALineNo'))
    
    # get trust metrics
    bfr_metrics = _calculate_metrics(bfr)
    # Slope analysis
    bfr_revenue_reserves, bfr_revenue_reserves_per_pupil = _slope_analysis(bfr, academies_y2, academies_y1)

    # volatility analysis
    bfr = pd.merge(bfr, academies[['Trust UPIN','Trust Balance']].rename(
        columns={'Trust UPIN': 'TrustUPIN'}), how='left', on='TrustUPIN')
    bfr = _volatility_analysis(bfr)
    
    bfr_metrics.drop_duplicates(inplace=True)
    
    use_columns = ["Y-2","Y-1","Y1","Y2","Y3","slope","slope_flag"]
    
    bfr_revenue_reserves.drop_duplicates(inplace=True)
    bfr_revenue_reserves = bfr_revenue_reserves[use_columns]
    bfr_revenue_reserves.rename(columns={
        "Y-2":"revenue_reserves_year_-2",
        "Y-1":"revenue_reserves_year_-1",
        "Y1":"revenue_reserves_year_0",
        "Y2":"revenue_reserves_year_1",
        "Y3":"revenue_reserves_year_2",
        "slope":"revenue_reserves_slope",
        "slope_flag":"revenue_reserves_slope_flag"}, inplace=True)
    
    
    bfr_revenue_reserves_per_pupil.drop_duplicates(inplace=True)
    bfr_revenue_reserves_per_pupil = bfr_revenue_reserves_per_pupil[use_columns]
    bfr_revenue_reserves_per_pupil.rename(columns={
        "Y-2":"revenue_reserves_year_per_pupil_-2",
        "Y-1":"revenue_reserves_year_per_pupil_-1",
        "Y1":"revenue_reserves_year_per_pupil_0",
        "Y2":"revenue_reserves_year_per_pupil_1",
        "Y3":"revenue_reserves_year_per_pupil_2",
        "slope":"revenue_reserves_year_per_pupil_slope",
        "slope_flag":"revenue_reserves_year_per_pupil_slope_flag"}, inplace=True)
    
    bfr_metrics = pd.merge(bfr_metrics, bfr_revenue_reserves, left_index=True, right_index=True)
    bfr_metrics = pd.merge(bfr_metrics, bfr_revenue_reserves_per_pupil, left_index=True, right_index=True)
    return bfr_metrics, bfr

In [ ]:
bfr_metrics, bfr = build_bfr_data('data/BFR_SOFA_raw.csv','data/BFR_3Y_raw.csv', academies.copy().reset_index(), academies.copy().reset_index(), academies.copy().reset_index())

### Timing Keep at the bottom

In [ ]:
print(f'Processing Time: {time.time() - start_time} seconds')

There are 327 duplicates in the academies outputs, and 346 in the maintained (excluding federations)


academy_ar has 10444 entries, 148 of the urns in this list are duplicated, though they look to be schools which have changed from SAT to MAT

The academies_list containes duplicated LAEstabs due to schools transitioning between SAT / MAT etc.

maintained_schools has 10650 entries, 347 of which are nulls. These can just be dropped

There are a few duplicates in federation data as well: